### PR TITLE
sha256 & default_store serialization support with feature gateway

### PR DESCRIPTION
**Pull request by cyberaurora**
Updated: 
1. add serde macro to `SparseMerkleTree` and its inner fields to adapt to event-sourcing system since sparse merkle tree won't be access concurrently in most cases.
2. add sha256 as a hasher candidate
3. docs badge in README

### CODE REVIEW

**Comment by jjyr** [comment]
In the most cases, we shouldn't serialize the whole merkle tree store, it is costly.

IMO we shouldn't introduce the serde into this crate, you should implement your own MerkleTreeStore struct & implment serde on it.

**Comment by cyberaurora** [comment]
Indeed, that's why I add serde macro with feature gateway. In event-sourcing system, we always keep the huge core data in memory and serialize it periodically to get rid of IO, as we've done in a pure-memory matcher [galois](https://github.com/uinb/galois). Besides, the `DefaultStore` is just a plain demo and may be meaningless without serialization, adding this wouldn't be harmful since the feature is disabled by default.

It is ok if you wouldn't accept this PR, but shall we use it in our own fork? :)

**Comment by jjyr** [comment]
Because this crate is dependent by many projects, we want to keep it simple enough, and less features.

In our system, we implement our own MerkleStore and convert the internal structs to a storage friendly format.

I wounld recommend you do the same thing, you can wrap sparse-merkle-tree into a crate to reduce duplicated work in different components, thus, you woundn't need to fork this repo.

The sha256 feature is acceptable.

**Comment by cyberaurora** [comment]
I see, thanks for your patience. We wouldn't like to bring any troubles to your projects, my apology. 
But using sparse-merkle-tree directly without modifications is a little inconvenient for us, if we need to serialize `SparseMerkleTree`, we must make all inner fields of `SparseMerkleTree` be serializable recursively, including `BranchKey`, `BranchNode`, `H256`, `MergeValue`. To use `serde-derive` feature to keep our code consistent,  we have to add serde macro to each type. 
More precisely, the only essential dependency this PR involved is `serde = "1.0"` which originally exists in dev-dependencies and can be optional either if modify unit-tests as well. 

Of course you don't have to meet all requirements. That's just a suggestion, feel free to close this PR at any time, or if convenient, may I beg you for leaving this PR open for a few days just in case you change your mind.

**Comment by jjyr** [comment]
The reason I don't want to introduce serde into this crate:

1. `serde` is not a common use case for sparse-merkle-tree. We recommended users store the SMT structs in a native storage format ( not json or toml ). So, I see you have your reason, but still, this feature is not a common use case of sparse-merkle-tree.
2. If we are dependent on serde, then we must follow serde's version. Sparse-merkle-tree crate is a fundamental crate for many projects. We don't want to release new versions just for track serde's version.
3. The design of sparse-merkle-tree is aiming to decouple the algorithm and the storage. That's the reason why we separate the storage implementation via a trait. So, of course, we also want to decouple the serialization from the crate.

> Let me explain. Using sparse-merkle-tree directly without modifications is a little inconvenient for us. If we need to serialize SparseMerkleTree, we must make all inner fields of SparseMerkleTree be serializable recursively, including BranchKey, BranchNode, H256, MergeValue. To use serde-derive feature to keep our code consistent, we have to add serde macro to each type.

I see this brings a little inconvenient, but all you need is to create a wrapper crate and implement serialization on `BranchKey, BranchNode, H256, MergeValue`, these types are very stabled, we expect these types not be changed in a long-term.

**Pull request closed without merging**
